# Generated by Django 2.1.7 on 2019-03-05 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_id', models.PositiveIntegerField()),
                ('telegram_channel_id', models.CharField(max_length=255)),
                ('telegram_token', models.CharField(max_length=255)),
                ('facebook_token', models.CharField(max_length=255)),
                ('vk_token', models.CharField(max_length=255)),
                ('vk_group_id', models.CharField(max_length=255)),
                ('twitter_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_work', models.ImageField(upload_to='')),
                ('new_work', models.ImageField(upload_to='')),
                ('rendered_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('old_work_year', models.PositiveSmallIntegerField()),
                ('new_work_year', models.PositiveSmallIntegerField()),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('tags', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm_admin.Account')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm_admin.Post'),
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm_admin.LinkType'),
        ),
    ]
