# Generated by Django 2.1.7 on 2019-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0002_postresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='twitter_token',
        ),
        migrations.AddField(
            model_name='account',
            name='twitter_token_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='twitter_token_secret',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
