# Generated by Django 2.1.7 on 2019-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0004_auto_20190305_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
