# Generated by Django 2.1.7 on 2019-03-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0005_account_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canvas_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='smm_admin.Post'),
        ),
    ]
