# Generated by Django 2.1.7 on 2019-03-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0006_auto_20190307_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rendered_picture',
            new_name='rendered_image',
        ),
    ]
