# Generated by Django 2.1.7 on 2019-03-08 20:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0007_auto_20190307_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('old_work_year', models.PositiveSmallIntegerField()),
                ('new_work_year', models.PositiveSmallIntegerField()),
                ('old_work_image', models.ImageField(blank=True, null=True, upload_to='suggested')),
                ('new_work_image', models.ImageField(blank=True, null=True, upload_to='suggested')),
                ('old_work_url', models.CharField(blank=True, default='', max_length=4096)),
                ('new_work_url', models.CharField(blank=True, default='', max_length=4096)),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), size=None)),
            ],
        ),
    ]
