# Generated by Django 2.1.7 on 2019-03-08 21:12

from django.db import migrations, models
import smm_admin.models.post_suggestion


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0008_postsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsuggestion',
            name='token',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
