# Generated by Django 2.1.7 on 2019-03-08 21:27

from django.db import migrations, models
import django.utils.timezone
import smm_admin.models.post_suggestion


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0009_postsuggestion_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postsuggestion',
            name='token',
            field=models.CharField(blank=True, default=smm_admin.models.post_suggestion.generate_token, max_length=36, unique=True),
        ),
    ]
