# Generated by Django 2.1.7 on 2019-03-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0010_auto_20190309_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsuggestion',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postsuggestion',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
