# Generated by Django 2.1.7 on 2019-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0011_auto_20190309_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facebook_group_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='twitter_username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='vk_group_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
