# Generated by Django 2.1.7 on 2019-03-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0013_auto_20190310_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postresult',
            name='raw',
            field=models.TextField(blank=True, default=''),
        ),
    ]
