# Generated by Django 2.1.7 on 2019-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0014_auto_20190310_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facebook_group_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
