# Generated by Django 2.1.7 on 2019-03-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0015_account_facebook_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
