# Generated by Django 2.1.7 on 2019-03-20 19:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0016_auto_20190313_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Vk'), (1, 'Facebook'), (2, 'Twitter'), (3, 'Telegram')])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='smm_admin.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook_group_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook_group_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='telegram_channel_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='telegram_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_token_key',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_token_secret',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vk_group_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vk_group_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vk_group_screen_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vk_token',
        ),
    ]
