# Generated by Django 2.1.7 on 2019-03-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0017_auto_20190320_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='smm_admin.Account'),
        ),
    ]
