# Generated by Django 2.1.7 on 2019-03-27 21:24

from django.db import migrations, models
import smm_admin.services.facebook
import smm_admin.services.telegram
import smm_admin.services.twitter
import smm_admin.services.vk


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0018_auto_20190320_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='type',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, smm_admin.services.vk.VkService), (1, smm_admin.services.facebook.FacebookService), (2, smm_admin.services.twitter.TwitterService), (3, smm_admin.services.telegram.TelegramService)]),
        ),
    ]
