# Generated by Django 2.1.7 on 2019-03-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0019_auto_20190328_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_work',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='old_work',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(blank=True, default=''),
        ),
    ]
