# Generated by Django 2.1.7 on 2019-04-07 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0022_auto_20190406_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostSuggestion',
        ),
        migrations.AddField(
            model_name='post',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Suggested'), (1, 'In Progress'), (2, 'Not Ready'), (3, 'Ready'), (4, 'OK'), (5, 'Failed')], default=2),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
