# Generated by Django 2.1.7 on 2019-04-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0023_auto_20190407_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='token',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
    ]
