# Generated by Django 2.1.7 on 2019-04-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0026_auto_20190423_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name_ru',
        ),
    ]
