# Generated by Django 2.1.7 on 2019-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0028_auto_20190426_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Failed'), (1, 'In Progress'), (2, 'Not Ready'), (3, 'Ready'), (4, 'OK'), (5, 'Deleted')], default=2),
        ),
    ]
