# Generated by Django 2.1.7 on 2019-04-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0029_auto_20190426_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
