# Generated by Django 2.1.7 on 2019-04-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0030_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Partially Failed'), (1, 'Failed'), (2, 'In Progress'), (3, 'Not Ready'), (4, 'Ready'), (5, 'OK'), (6, 'Deleted')], default=3),
        ),
    ]
