# Generated by Django 2.1.7 on 2019-05-13 10:39

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smm_admin', '0031_auto_20190427_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
